input_json_dir: '../input-json-data'
output_excel_dir: '../output'

sonarqube_api:
  endpoint_search_issues: '/api/issues/search'
  endpoint_search_hotspots: '/api/hotspots/search'
  sonarqube_url: '###############'
  project_key: '###############'
  auth_token: '###############'

sonarqube_api_parser:
  output_columns_hotspots: ['module', 'vulnerabilityProbability', 'securityCategory', 'message', 'component', 'line', 'project', 'key']
  output_columns_issues: ['module', 'type', 'severity', 'message', 'debt', 'component', 'line', 'rule', 'project', 'key']
